# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kestrelrb}
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kevin E. Hunt"]
  s.date = %q{2009-10-29}
  s.description = %q{Kestrel is a queue server written in Scala that runs on the JVM and has a memcached wire API.}
  s.email = %q{kevin@kev.in}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/kestrelrb.rb",
     "test/helper.rb",
     "test/test_kestrelrb.rb"
  ]
  s.homepage = %q{http://github.com/kevn/kestrelrb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Ruby interface to Kestrel queues}
  s.test_files = [
    "test/helper.rb",
     "test/test_kestrelrb.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<memcache-client>, [">= 1.7.5"])
    else
      s.add_dependency(%q<memcache-client>, [">= 1.7.5"])
    end
  else
    s.add_dependency(%q<memcache-client>, [">= 1.7.5"])
  end
end

